const movies = [
    {
        _id: "1",
        name: "«Роллинг Стоунз» в изгнании",
        duration: 61,
        link: "https://api.nomoreparties.co/uploads/stones_in_exile_b2f1b8f4b7.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=UXcqcdYABFw", 
    },
    {
        _id: "2",
        name: "All Tomorrow's Parties",
        duration: 82,
        link: "https://api.nomoreparties.co/uploads/all_tommoros_parties_33a125248d.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=D5fBhbEJxEU",
    },
    {
        _id: "3",
        name: "Без обратного пути",
        duration: 104,
        link: "https://api.nomoreparties.co/uploads/blur_a43fcf463d.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=6iYxdghpJZY",
    },
    {
        _id: "4",
        name: "Bassweight",
        duration: 61,
        link: "https://api.nomoreparties.co/uploads/zagruzhennoe_113f557116.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=dgSyC6me-jQ"
    },
    {
        _id: "5",
        name: "Taqwacore: The Birth of Punk Islam",
        duration: 80,
        link: "https://api.nomoreparties.co/uploads/taqwacore2_2f487d2e74.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=JMZ8DO9F4Mo",
    },
    {
        _id: "6",
        name: "Фавела на взрыве",
        duration: 80,
        link: "https://api.nomoreparties.co/uploads/881707734_640_d6a3a43358.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=Cugdwa7mndA",
    },
    {
        _id: "7",
        name: "Постеры, сошедшие со стен",
        duration: 72,
        link: "https://api.nomoreparties.co/uploads/posters_came_from_the_walls_2009_001_posters_180fe1a19f.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=VFMU3crg0sM",
    },
    {
        _id: "8",
        name: "Soul Power",
        duration: 92,
        link: "https://api.nomoreparties.co/uploads/images_5bfcbf36e6.jpeg",
        trailerLink: 	"https://www.youtube.com/watch?v=8OprNgiOq-I",
    },
    {
        _id: "9",
        name: "196 ударов в минуту",
        duration: 60,
        link: "https://api.nomoreparties.co/uploads/zagruzhennoe_1_fd5faff237.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=GsDRVpdgNJ4",
    },
    {
        _id: "10",
        name: " Hit So Hard: Школа жизни Патти Шемель",
        duration: 103,
        link: "https://api.nomoreparties.co/uploads/images_244e1fd56f.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=DMvFMeaGj_w",
    },
    {
        _id: "11",
        name: "Баллада о Дженезисе и Леди Джей",
        duration: 65,
        link: "https://api.nomoreparties.co/uploads/ballad_of_genesis_and_lady_jaye_10c27afa96.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=d8BX2FDrogo",
    },
    {
        _id: "12",
        name: "Виллалобос",
        duration: 110,
        link: "https://api.nomoreparties.co/uploads/590x400_2eccd40a93.jpeg",
        trailerLink: "https://www.kinopoisk.ru/film/586534/video/56500/",
    },
    {
        _id: "13",
        name: "Между дьяволом и глубоким синим морем",
        duration: 89,
        link: "https://api.nomoreparties.co/uploads/8647b36126befd6051c83ae66339d7f71ecbaa0d_752489df96.jpeg",
        trailerLink: "https://youtu.be/qUmIgNwRCP4",
    },
    {
        _id: "14",
        name: "Ритмы свободы",
        duration: 73,
        link: "https://api.nomoreparties.co/uploads/1_6a9e0669ca.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=VvKWRtF3eNY",
    },
    {
        _id: "15",
        name: "Сепарадо!",
        duration: 84,
        link: "https://api.nomoreparties.co/uploads/zagruzhennoe_cba9c9f900.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=r2IfD-6iS3Y",
    },
    {
        _id: "16",
        name: "С ног на голову: История Creation records",
        duration: 101,
        link: "https://api.nomoreparties.co/uploads/b452eefcd7d441e79b2f5ae291b7_2c0c62fa89.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=b3kA_8NrinA",
    }, 
    {
        _id: "17",
        name: "Я всё ещё здесь",
        duration: 108,
        link: "https://api.nomoreparties.co/uploads/280x178_2_f2eee77cae.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=cDwdYsOeSXw",
    },
    {
        _id: "18",
        name: "Большие надежды",
        duration: 72,
        link: "https://api.nomoreparties.co/uploads/zagruzhennoe_1_dc1a2c8f7d.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=D2q38mu3MKs",
    },
    {
        _id: "19",
        name: "Задний двор",
        duration: 73,
        link: "https://api.nomoreparties.co/uploads/Backyard_327_3_2151980c5c.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=TShW9LAcmCg",
    },
    {
        _id: "20",
        name: "Еще одно слово на П",
        duration: 98,
        link: "https://api.nomoreparties.co/uploads/zagruzhennoe_2_5f87844408.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=zZkWHZ3hJtY",
    },
    {
        _id: "21",
        name: "Боб Марли: Рэгги навсегда",
        duration: 144,
        link: "https://api.nomoreparties.co/uploads/b1_3385dd88fe.jpeg",
        trailerLink: "https://www.youtube.com/watch?v=YvNlAZ3xqwI",
    },

];

export default movies;